Change to css timeline
hillairet/study-4-canadian-citizenship-test pull request #1
Opened 2023-06-20 14:25 UTC by hillairet

Switched to a much better timeline using only CSS for rendering.
Javascript still used to load the data into HTML.

2023-06-20 17:39 UTC, rahulpatidar0191 requested changes
Some typos

2023-06-20 17:39 UTC, rahulpatidar0191 commented on data.js
> +          {"date": "1944-06-06", "title": "D-Day, invasion of Normandy", "description": "15,000 Canadian troops captune Juno beach"},
```suggestion
          {"date": "1944-06-06", "title": "D-Day, invasion of Normandy", "description": "15,000 Canadian troops captured Juno beach"},
```

2023-06-20 17:39 UTC, rahulpatidar0191 commented on data.js
> +          {"date": "1945-09-02", "title": "End of World War II", "description": "More than 1 million Canadians and Newfoundlanders served in Wolrd War II"},
```suggestion
          {"date": "1945-09-02", "title": "End of World War II", "description": "More than 1 million Canadians and Newfoundlanders served in World War II"},
```

2023-06-20 17:39 UTC, rahulpatidar0191 commented on data.js
> +          {"date": "1849-02-27", "title": "The governor of United Canada, Lorg Egin, introduces a responsible government", "description": "Lafontaine, a champion of democracy and French language righ
```suggestion
          {"date": "1849-02-27", "title": "The governor of United Canada, Lord Elgin, introduces a responsible government", "description": "Lafontaine, a champion of democracy and French language rights, becomes the first leader of a responsible government in the Canadas"},
```

2023-06-20 17:39 UTC, rahulpatidar0191 commented on data.js
> +          {"date": "1867-07-01", "title": "The Birtish North America Act is enacted", "description": ["The Dominion of Canada is born, term used for 100 years.", "July 1st is referred to as \"Dominio
```suggestion
          {"date": "1867-07-01", "title": "The British North America Act is enacted", "description": ["The Dominion of Canada is born, term used for 100 years.", "July 1st is referred to as \"Dominion Day\" till 1982"]},
```

2023-06-20 17:39 UTC, rahulpatidar0191 commented on data.js
> +          {"date": "1880-09-01", "title": "Transfer of the Artic Islands from Britain to the North West Territories"},
```suggestion
          {"date": "1880-09-01", "title": "Transfer of the Arctic Islands from Britain to the North West Territories"},
```

2023-06-20 17:39 UTC, rahulpatidar0191 commented on data.js
> +          {"date": "1885-11-07", "title": "The Canadian Pacific Ralway's \"Ribbons of steel\" is completed", "emoji": "🛤️"},
```suggestion
          {"date": "1885-11-07", "title": "The Canadian Pacific Railway's \"Ribbons of steel\" is completed", "emoji": "🛤️"},
```

2023-06-20 17:39 UTC, rahulpatidar0191 commented on data.js
> +          {"date": "1933-06-01", "title": "Unemployment reaches 27% an many businesses are wipedout.", "emoji": "📉"},
```suggestion
          {"date": "1933-06-01", "title": "Unemployment reaches 27% and many businesses are wiped out.", "emoji": "📉"},
```

2023-06-20 18:03 UTC, hillairet commented
@rahulpatidar0191 Good eye for typos! Thanks!
Any feedback on the overall look?

2023-06-20 18:12 UTC, rahulpatidar0191 commented
The overall look is good. Grouping them with emoji is a clever idea. 

One very minor thing I noticed is the single points are missing a bullet. For eg: John Cabot is missing a bullet but the next point has it. Again, minor thing 

![image](https://github.com/hillairet/canadian-citizenship-test-history/assets/42219389/8639bca5-5770-4757-99d3-c1c722235c92)

2023-06-20 18:34 UTC, hillairet commented
> The overall look is good. Grouping them with emoji is a clever idea.
> 
> One very minor thing I noticed is the single points are missing a bullet. For eg: John Cabot is missing a bullet but the next point has it. Again, minor thing
> 
> ![image](https://user-images.githubusercontent.com/42219389/247218631-8639bca5-5770-4757-99d3-c1c722235c92.png)

It's actually by design!  :sweat_smile: 
I thought it'd be better to separate between one description and multiple but clearly it looks off since you thought it was a mistake.
I'll put a bullet point every time to make it consistent.

2023-06-24 17:42 UTC, rahulpatidar0191 approved these changes

2023-06-24 20:58 UTC, merged